### ISSUE TITLE
why download dataset do not include annotation ??

### ISSUE THREAD

**Issue by CarlHuangNuc** [SoccerNet/sn-mvfoul#2]
why download dataset do not include annotation ??  only include action video ??

**Comment by CarlHuangNuc** [comment]
Where we can get the annotations files ?

def label2vectormerge(folder_path, split, num_views):
	path_annotations = os.path.join(folder_path, split)
	path_annotations = os.path.join(path_annotations, "annotations.json")

**Comment by SilvioGiancola** [comment]
Our datasets contain annotations for the "train", "valid" and "test" sets. We do not provide annotations for the "challenge" set to prevent overfitting on that set.

**Comment by SilvioGiancola** [comment]
each zip has a file "annotations.json"
