### ISSUE TITLE
How can I get high resolution data?

### ISSUE THREAD

**Issue by BupyeongHealer** [SoccerNet/sn-mvfoul#4]
First, Thanks for opening this challenge.

When I get a data using below command, resolution of the data is too low. 
```
from SoccerNet.Downloader import SoccerNetDownloader as SNdl
mySNdl = SNdl(LocalDirectory="path/to/SoccerNet")
mySNdl.downloadDataTask(task="mvfouls", split=["train","valid","test","challenge"], password="enter password")
```
I want to get high resolution data. How can I get high resolution data?
Let me know the command for downloading high resolution data.

**Comment by BupyeongHealer** [comment]
I used below command. It works!

```
from SoccerNet.Downloader import SoccerNetDownloader as SNdl
mySNdl = SNdl(LocalDirectory="./SoccerNet-720p")
mySNdl.downloadDataTask(task="mvfouls", split=["train","valid","test","challenge"], version="720p")
```

**Comment by BupyeongHealer** [comment]
The train_720p.zip file was damaged. I can't open this file. 
Can you check this issue?

**Comment by SilvioGiancola** [comment]
@BupyeongHealer can you please make sure your file downloaded completely? You might have stopped it while it was downloading.
@heldJan can you please check on your side too? I am remote and don't have a strong enough connection right now to DL 13.3GB.

**Comment by heldJan** [comment]
@BupyeongHealer, you might not have downloaded the full dataset. Everything's working fine on my site. Could you double-check that you've completely downloaded the dataset and let me know if it works. :)

**Comment by SilvioGiancola** [comment]
@BupyeongHealer Are you on MacOS? I experienced a similar error with the "Archive Utility" (default) on MacOS but I was able to unzip with the app "The Unarchiver".

**Comment by BupyeongHealer** [comment]
@SilvioGiancola @heldJan I'm on Ubuntu 22.04. I also experience same error.
Fortunately, now i can unzip the train file.
The issue came from the using default unzip extractor!
Thanks for sharing your expereince. @SilvioGiancola

**Comment by SilvioGiancola** [comment]
Can you please write here what unzip extractor you used on Ubuntu 22.04? It could be useful for other participants. Thanks

**Comment by BupyeongHealer** [comment]
I just used the command to unzip the file. Before that I used default GUI unzip extractor to unzip the files.

```
sudo apt-get install unzip
unzip file.zip -d destination_folder
```
