### ISSUE TITLE
Dataset NDA Form Access Denied

### ISSUE THREAD

**Issue by md-hassan** [SoccerNet/sn-mvfoul#6]
Hello, 

Thank you for the great work!

We are a team of students who want to participate in the SoccerNet-MVFoul challenge. We are trying to fill the NDA Form ([linked in the readme](https://github.com/SoccerNet/sn-mvfoul?tab=readme-ov-file#soccernet-mvfoul)) for access, but it says it is no longer accepting responses. 

Is the challenge over? Is there any other way to get access to the data? 

Thanks,
Yusuf

**Comment by SilvioGiancola** [comment]
Hi @md-hassan , 

The link was down in the last 4-5 days. It is back online now. Please give it a try.

Cheers,
